trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: GH_TOKEN
- name: GITHUB_REPO
  value: 'bojanazdravkovska/mg-clean'
- name: GITHUB_BRANCH
  value: 'master'

steps:
- checkout: self

- script: |
    git config --global user.email "azure-pipeline@yourdomain.com"
    git config --global user.name "Azure Pipeline"
    
    git remote add github https://$(GH_TOKEN)@github.com/$(GITHUB_REPO).git
    git push github HEAD:$(GITHUB_BRANCH) --force
  displayName: 'Push changes to GitHub'
